name: complex

on: push

jobs:
    ubuntu:
        name: First Job
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Print Date
          run: date "+%Y-%m-%d %H:%M:%S"
            
    windows:
        name: Second job
        runs-on: windows-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Print Date
          run: Get-Date  # Prints date in PowerShell on Windows
          shell: powershell
    macos:
        name: Third Job
        runs-on: macos-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Print Date
          run: date
            
    depends:
        needs: [ubuntu, windows, macos]
        name: Fourth job
        runs-on: windows-latest
        steps:
        - name: Step one
          uses: actions/checkout@v2
        - name: Step two
          run: Get-Date  # Prints date in PowerShell on Windows
          shell: powershell
          
